### ISSUE TITLE
module is not defined

### ISSUE THREAD

**Issue by SirZach** [switchfly/ember-cli-mocha#31]
When upgrading from 0.2.1 to 0.3.1, I now get an error referencing module. This file is the culprit (not a file created by me).

```
define("nui/tests/adapters/application.jshint", 
  [],
  function() {
    "use strict";
    module('JSHint - adapters');
    test('adapters/application.js should pass jshint', function() { 
      ok(true, 'adapters/application.js should pass jshint.'); 
    });
  });//# sourceURL=nui/tests/adapters/application.jshint.js
```

**Comment by rwjblue** [comment]
@SirZach - What version of ember-cli are you using?  Prior to 0.1.11, ember-cli itself would generate QUnit tests for JSHint failures.

**Comment by SirZach** [comment]
I'm using version 0.1.4 of ember-cli

**Comment by rwjblue** [comment]
OK, so here is what is happening:

* ember-cli is generating QUnit style tests for JSHint failures (and has been since at least 0.0.45).
* These files were completely ignored by the test loader (its default `shouldLoadModule` only checked for `/[-_]test$/`) in versions prior to 0.3.0. See [here](https://github.com/ember-cli/ember-cli-test-loader/blob/c6006a11515c756d115bb5209103a22c2e9554a0/test-loader.js#L12-L14).
* In 0.3.0+ of ember-cli-mocha (and 0.1.10+ of ember-cli) the JSHint tests can now be customized for specific test formats, and we now generate mocha style JSHint tests.
* Due to ^^ we are now loading JSHint tests automatically in ember-cli-mocha. See [here](https://github.com/switchfly/ember-cli-mocha/blob/v0.3.1/vendor/ember-cli-mocha/test-loader.js#L9-L11).

So, you basically can either update to ember-cli to 0.1.11 or downgrade ember-cli-mocha to 0.2.1.

**Comment by SirZach** [comment]
Thanks for the quick feedback! I'll reopen if I after I upgrade to ember-cli 0.1.11 I still see problems. Thanks!

**Comment by aaronrenner** [comment]
Upgrading to ember-cli 0.1.11 worked for me. Thanks @SirZach for posting the issue, and thanks @rwjblue for posting the answer.

**Comment by westonplatter** [comment]
I'm on ember-cli 0.2.1 and still hitting `'module' is not defined`, 

```sh
acceptance/root-page-test.js: line 10, col 1, 'module' is not defined.
```

From what I read, JSHint did not recognize that `module` is predefined via ES6. Therefore, I added `module` to the list of predefined keywords in the my_ember_app/tests/.jshintrc file,

```json
{
  "predef": [
    "document",
    // .... 
    "module"
  ],
  "node": false,
  // ...
  "esnext": true
}
```
